# Generated by Django 6.1 on 2026-08-14 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('can_be_stored', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRescueOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150)),
                ('organization_type', models.CharField(choices=[('NGO', 'NGO / Food Rescue Organization'), ('SHELTER', 'Shelter / Community Center'), ('ANIMAL', 'Animal Welfare Organization')], max_length=50)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_prepared', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.fooditem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LeftoverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('DISCOUNTED', 'Discounted & Sold'), ('DONATED', 'Donated'), ('STORED', 'Stored'), ('STAFF', 'Given to Staff'), ('WASTED', 'Wasted')], max_length=20)),
                ('waste_reason', models.CharField(blank=True, choices=[('OVERPRODUCTION', 'Overproduction'), ('LOW_DEMAND', 'Low Demand'), ('SPOILAGE', 'Spoilage'), ('PREPARATION_ERROR', 'Preparation Error'), ('CUSTOMER_LEFTOVER', 'Customer Leftover'), ('OTHER', 'Other')], max_length=30)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.dailyfoodrecord')),
                ('donation_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wastage.foodrescueorganization')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.fooditem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('leftover_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.leftoverrecord')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.restaurant'),
        ),
        migrations.CreateModel(
            name='StorageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_stored', models.PositiveIntegerField()),
                ('storage_method', models.CharField(max_length=50)),
                ('use_by_date', models.DateField()),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('leftover_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.leftoverrecord')),
            ],
        ),
    ]
