# Generated by Django 6.1 on 2026-08-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0002_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftoverrecord',
            name='people_helped',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
