# Generated by Django 6.1 on 2026-08-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0003_leftoverrecord_people_helped'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftoverrecord',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('G', 'Grams'), ('L', 'Litres'), ('ML', 'Millilitres'), ('PCS', 'pieces')], default='KG', max_length=10),
        ),
        migrations.AlterField(
            model_name='leftoverrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
