# Generated by Django 6.1 on 2026-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0004_leftoverrecord_unit_alter_leftoverrecord_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftoverrecord',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
