# Generated by Django 6.1 on 2026-08-28 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0005_leftoverrecord_quantity_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrescueorganization',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_rescue_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
