# Generated by Django 6.1 on 2026-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0006_foodrescueorganization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrescueorganization',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
