# Generated by Django 6.1 on 2026-08-31 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastage', '0007_foodrescueorganization_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('leftover_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.leftoverrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wastage.foodrescueorganization')),
            ],
        ),
    ]
